kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airtrail-uploads
  namespace: airtrail
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sbs-default-retain
---
