apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: twitter-profile-pic
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: twitter-profile-pic
  updatePolicy:
    updateMode: "Auto"
