apiVersion: v1
kind: Namespace
metadata:
  name: grocy
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grocy
  namespace: grocy
spec:
  chart:
    repository: https://k8s-at-home.com/charts/
    name: grocy
    version: 6.3.1
  maxHistory: 4
  skipCRDs: false
  values:
    env:
      TZ: Europe/London
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/frontend-entry-points: http,https
        traefik.ingress.kubernetes.io/redirect-entry-point: https
        traefik.ingress.kubernetes.io/redirect-permanent: "true"
      hosts:
      - host: grocy.cluster.fun
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - grocy.cluster.fun
        secretName: grocy
    persistence:
      config:
        enabled: true
