apiVersion: v1
kind: Secret
metadata:
  name: mealie
  namespace: mealie
  annotations:
    kube-1password: 7ibib7oafxbxkvofnd4oxcr3qy
    kube-1password/vault: Kubernetes
    kube-1password/secret-text-parse: "true"
type: Opaque

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      priorityClassName: critical
      containers:
      - name: frontend
        image: ghcr.io/mealie-recipes/mealie:v3.2.1
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: mealie
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TOKEN_TIME
          value: "720"
        - name: DB_ENGINE
          value: postgres
        - name: POSTGRES_DB
          value: mealie
        - name: RECIPE_PUBLIC
          value: "false"
        - name: RECIPE_SHOW_NUTRITION
          value: "true"
        - name: RECIPE_SHOW_ASSETS
          value: "true"
        - name: RECIPE_LANDSCAPE_VIEW
          value: "true"
        - name: RECIPE_DISABLE_COMMENTS
          value: "false"
        - name: RECIPE_DISABLE_AMOUNT
          value: "false"
        - name: ALLOW_SIGNUP
          value: "false"
        - name: BASE_URL
          value: "https://mealie.cluster.fun"
        ports:
        - containerPort: 9000
          name: web
        volumeMounts:
          - mountPath: /app/data
            name: data
        resources:
          requests:
            cpu: 200m
            memory: 500M
          limits:
            cpu: 1000m
            memory: 500M
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mealie

---

apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: mealie
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: web
    name: web
  selector:
    app: mealie
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie
  namespace: mealie
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - mealie.cluster.fun
    secretName: mealie-ingress
  rules:
  - host: mealie.cluster.fun
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: mealie
            port:
              name: web
