kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mealie
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: sbs-default-retain
---
