# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   annotations:
#     pv.kubernetes.io/provisioned-by: csi.scaleway.com
#   finalizers:
#   - kubernetes.io/pv-protection
#   - external-attacher/csi-scaleway-com
#   name: pvc-afe7fbb6-1f5a-4169-bad1-c9d43752ee7a
# spec:
#   accessModes:
#   - ReadWriteOnce
#   capacity:
#     storage: 2Gi
#   csi:
#     driver: csi.scaleway.com
#     fsType: ext4
#     volumeAttributes:
#       encrypted: "false"
#       storage.kubernetes.io/csiProvisionerIdentity: 1646426415842-8081-csi.scaleway.com
#     volumeHandle: fr-par-1/efbe7dc1-4660-4db8-a3b4-42114075a318
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: scw-bssd
#   volumeMode: Filesystem

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mealie
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
