apiVersion: v1
kind: Service
metadata:
  name: text-to-dxf
  namespace: text-to-dxf
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: web
    name: web
  selector:
    app: text-to-dxf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-to-dxf
  namespace: text-to-dxf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-to-dxf
  template:
    metadata:
      labels:
        app: text-to-dxf
    spec:
      containers:
      - name: web
        image: rg.fr-par.scw.cloud/averagemarcus/text-to-dxf:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: web
        resources:
          requests:
            memory: 50Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: text-to-dxf
  namespace: text-to-dxf
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - text-to-dxf.cluster.fun
    secretName: text-to-dxf-ingress
  rules:
  - host: text-to-dxf.cluster.fun
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: text-to-dxf
            port:
              number: 80
