apiVersion: v1
kind: Service
metadata:
  name: text-to-dxf
  namespace: text-to-dxf
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: web
    name: web
  selector:
    app: text-to-dxf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-to-dxf
  namespace: text-to-dxf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-to-dxf
  template:
    metadata:
      labels:
        app: text-to-dxf
    spec:
      containers:
      - name: web
        image: docker.cluster.fun/averagemarcus/text-to-dxf:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: web
        resources:
          requests:
            memory: 100Mi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: text-to-dxf
  namespace: text-to-dxf
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  tls:
  - hosts:
    - text-to-dxf.cluster.fun
    secretName: text-to-dxf-ingress
  rules:
  - host: text-to-dxf.cluster.fun
    http:
      paths:
      - path: /
        backend:
          serviceName: text-to-dxf
          servicePort: 80
