apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubectl-apply-files
  namespace: tekton-pipelines
spec:
  params:
  - name: DIRECTORY
    description: Directory of kubernetes manifest files
  steps:
  - name: kubectl-apply
    image: gcr.io/cloud-builders/kubectl
    script: |
      kubectl apply --recursive -f $(params.DIRECTORY)
