apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubectl-apply-inline
  namespace: tekton-pipelines
spec:
  params:
  - name: MANIFEST
    description: Content of the resource to deploy
  steps:
  - name: kubectl-apply
    image: gcr.io/cloud-builders/kubectl
    script: |
      echo "$(params.MANIFEST)" | kubectl apply -f -
