apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pr-status
  namespace: tekton-pipelines
spec:
  params:
  - name: REPO
    description: The name of the repo
  - name: SHA
    description: The git SHA to update the status of
  - name: STATE
    description: The state to set the status to (pending, success, error, failure or warning)
    default: "pending"
  steps:
  - name: pr-status-update
    image: docker.cluster.fun/averagemarcus/gitea-pr-state:latest
    env:
    - name: ACCESS_TOKEN
      valueFrom:
        secretKeyRef:
          name: gitea-access-token
          key: access-token
    args:
    - "$(params.REPO)"
    - "$(params.SHA)"
    - "$(params.STATE)"
