apiVersion: v1
kind: Service
metadata:
  name: black-hole
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9090
    name: web
  selector:
    app: black-hole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: black-hole
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: black-hole
  template:
    metadata:
      labels:
        app: black-hole
    spec:
      containers:
      - name: black-hole
        image: averagemarcus/black-hole:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          name: web
        resources:
          limits:
            memory: 10Mi
          requests:
            memory: 10Mi

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: black-hole
  namespace: kube-system
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: black-hole
            port:
              number: 80
