apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: feed-fetcher
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: feed-fetcher
  updatePolicy:
    updateMode: "Auto"
