apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: git
  name: git-data-git-0
  namespace: gitea
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: sbs-default-retain
