apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: csi.scaleway.com
  creationTimestamp: "2020-05-02T15:38:54Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/csi-scaleway-com
  name: pvc-02bd903f-e5ac-4c9f-a976-9fe995a352b2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: csi.scaleway.com
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1588413765965-1847-csi.scaleway.com
    volumeHandle: fr-par-1/2ef4f017-2d41-4662-bfa4-df0dcf2085a1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: scw-bssd-retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: csi.scaleway.com
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: git
  name: git-data-git-0
  namespace: gitea
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: scw-bssd-retain
  volumeMode: Filesystem
  volumeName: pvc-02bd903f-e5ac-4c9f-a976-9fe995a352b2
