apiVersion: v1
kind: Service
metadata:
  name: bsky-screenshot
  namespace: bsky-screenshot
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: web
    name: web
  selector:
    app: bsky-screenshot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsky-screenshot
  namespace: bsky-screenshot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bsky-screenshot
  template:
    metadata:
      labels:
        app: bsky-screenshot
    spec:
      containers:
      - name: web
        image: rg.fr-par.scw.cloud/averagemarcus/bsky-screenshot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
        resources:
          limits:
            memory: 20Mi
          requests:
            memory: 20Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bsky-screenshot
  namespace: bsky-screenshot
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - bsky-screenshot.cluster.fun
    secretName: bsky-screenshot-ingress
  rules:
  - host: bsky-screenshot.cluster.fun
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: bsky-screenshot
            port:
              number: 80

