apiVersion: v1
kind: Secret
metadata:
  name: git-sync-github
  namespace: git-sync
  annotations:
    kube-1password: cfo2ufhgem57clbscxetxgevue
    kube-1password/vault: Kubernetes
    kube-1password/password-key: token
type: Opaque
data:
---
apiVersion: v1
kind: Secret
metadata:
  name: git-sync-gitea
  namespace: git-sync
  annotations:
    kube-1password: b7kpdlcvt7y63bozu3i4j4lojm
    kube-1password/vault: Kubernetes
    kube-1password/password-key: token
type: Opaque
data:
---
apiVersion: v1
kind: Secret
metadata:
  name: git-sync-gitlab
  namespace: git-sync
  annotations:
    kube-1password: t47v3xdgadiifgoi4wmqibrlty
    kube-1password/vault: Kubernetes
    kube-1password/password-key: token
type: Opaque
data:
---
apiVersion: v1
kind: Secret
metadata:
  name: git-sync-bitbucket
  namespace: git-sync
  annotations:
    kube-1password: adrki45krr2tq34sug7dhdk5iy
    kube-1password/vault: Kubernetes
    kube-1password/password-key: token
type: Opaque
data:
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: git-sync
  namespace: git-sync
spec:
  schedule: "0 */1 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        cronjob: git-sync
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: sync
            image: harbor.cluster.fun/averagemarcus/git-sync:latest
            imagePullPolicy: Always
            env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: git-sync-github
                  key: token
            - name: GITEA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: git-sync-gitea
                  key: token
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: git-sync-gitlab
                  key: token
            - name: BITBUCKET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: git-sync-bitbucket
                  key: token
          restartPolicy: Never
