apiVersion: v1
kind: Namespace
metadata:
  name: goldilocks
  labels:
    goldilocks.fairwinds.com/enabled: "true"

---

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: goldilocks
spec:
  chart:
    repository: https://charts.fairwinds.com/stable
    name: goldilocks
    version: 2.3.1
  maxHistory: 4
  values:
    installVPA: true
