apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-values
  namespace: harbor
  annotations:
    kube-1password: igey7vjjiqmj25v64eck7cyj34
    kube-1password/vault: Kubernetes
    kube-1password/secret-text-key: values.yaml
type: Opaque
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  chart:
    repository: https://helm.goharbor.io
    name: harbor
    version: 1.3.2
  maxHistory: 4
  skipCRDs: false
  valuesFrom:
  - secretKeyRef:
      name: harbor-values
      namespace: harbor
      key: values.yaml
      optional: false
  values:
    portal:
      resources:
        requests:
          memory: 64Mi
    core:
      resources:
        requests:
          memory: 64Mi
    jobservice:
      resources:
        requests:
          memory: 64Mi
    registry:
      registry:
        resources:
          requests:
            memory: 64Mi
      controller:
        resources:
          requests:
            memory: 64Mi

