apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: website-to-remarkable
  namespace: inlets
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  tls:
  - hosts:
    - website-to-remarkable.cluster.fun
    secretName: website-to-remarkable-ingress
  rules:
  - host: website-to-remarkable.cluster.fun
    http:
      paths:
      - path: /
        backend:
          serviceName: auth-proxy
          servicePort: 80
