apiVersion: v1
kind: Secret
metadata:
  name: docker-config
  namespace: anniversary
  annotations:
    kube-1password: i6ngbk5zf4k52xgwdwnfup5bby
    kube-1password/vault: Kubernetes
    kube-1password/secret-text-key: .dockerconfigjson
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30=
---
apiVersion: v1
kind: Service
metadata:
  name: anniversary
  namespace: anniversary
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: web
    name: web
  selector:
    app: anniversary
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anniversary
  namespace: anniversary
spec:
  replicas: 0
  selector:
    matchLabels:
      app: anniversary
  template:
    metadata:
      labels:
        app: anniversary
    spec:
      imagePullSecrets:
        - name: docker-config
      containers:
      - name: web
        image: rg.fr-par.scw.cloud/averagemarcus-private/11-year-anniversary:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
        resources:
          limits:
            memory: 5Mi
          requests:
            memory: 5Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anniversary
  namespace: anniversary
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - 11-year-anniversary.marcusnoble.co.uk
    secretName: anniversary-ingress
  rules:
  - host: 11-year-anniversary.marcusnoble.co.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: anniversary
            port:
              number: 80
