{
 "title": "Analytics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "marcusnoble.co.uk,til.marcusnoble.co.uk,dash.cluster.fun,tweet.cluster.fun,base64.cluster.fun,feed-fetcher.cluster.fun,cors-proxy.cluster.fun"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Per Status Code",
   "type": "stat",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({k8s_app=\"traefik-ingress-lb\"} | json | RequestHost=~\"${host:text}\" error=\"\" [$__interval]))",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "sum by (DownstreamStatus) (count_over_time({k8s_app=\"traefik-ingress-lb\"} | json | RequestHost=~\"${host:text}\" error=\"\" [$__interval]))",
     "legendFormat": "{{DownstreamStatus}}"
    }
   ]
  },
  {
   "title": "Top Viewed Pages",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "topk(25, sum by (RequestPath) (count_over_time({k8s_app=\"traefik-ingress-lb\"} | json | RequestHost=~\"${host:text}\" error=\"\" RequestPath=~\"^/([a-zA-Z0-9\\\\-_]+(/|(ht|x)ml?)?)?$\" DownstreamStatus=~\"2.+\" [$__interval])))",
     "legendFormat": "{{RequestPath}}"
    }
   ]
  },
  {
   "title": "Top Referers",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "topk(25, sum by (request_Referer) (count_over_time({k8s_app=\"traefik-ingress-lb\"} | json | RequestHost=~\"${host:text}\" error=\"\" request_Referer!=\"\" request_Referer!~\"https?://.*${host:text}/?.*\" \n | label_format request_Referer=`{{ regexReplaceAll \"https?://(.*)google.co.uk\" .request_Referer \"Google UK\" }}`\n | label_format request_Referer=`{{ regexReplaceAll \"https?://(.*)google..+\" .request_Referer \"Google\" }}`\n | label_format request_Referer=`{{ regexReplaceAll \"https?://t.co/.*\" .request_Referer \"Twitter\" }}` \n | label_format request_Referer=`{{ regexReplaceAll \"https?://.*bing.com/.*\" .request_Referer \"Bing\" }}` \n | label_format request_Referer=`{{ regexReplaceAll \"https?://.*baidu.com/.*\" .request_Referer \"Baidu\" }}` \n | label_format request_Referer=`{{ regexReplaceAll \"https?://.*duckduckgo.com/?\" .request_Referer \"DuckDuckGo\" }}` \n[$__interval])))",
     "legendFormat": "{{request_Referer}}"
    }
   ]
  },
  {
   "title": "Requests Per Status Code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "No. of Requests" }
   ],
   "targets": [
    {
     "expr": "sum by (DownstreamStatus) (count_over_time({k8s_app=\"traefik-ingress-lb\"} | json | RequestHost=~\"${host:text}\" error=\"\" [$__interval]))",
     "legendFormat": "{{DownstreamStatus}}"
    }
   ]
  },
  {
   "title": "Top 404",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "topk(25, sum by (RequestPath) (count_over_time({k8s_app=\"traefik-ingress-lb\"} | json | RequestHost=~\"${host:text}\" error=\"\" DownstreamStatus=\"404\" [$__interval])))",
     "legendFormat": "{{RequestPath}}"
    }
   ]
  },
  {
   "title": "Top User Agents",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "topk(25, sum by (request_User_Agent) (count_over_time({k8s_app=\"traefik-ingress-lb\"} | json | RequestHost=~\"${host:text}\" error=\"\" request_User_Agent!=\"\" [$__interval])))",
     "legendFormat": "{{request_User_Agent}}"
    }
   ]
  },
  {
   "title": "All Requests",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (RequestMethod, RequestPath, DownstreamStatus) (count_over_time({k8s_app=\"traefik-ingress-lb\"} | json | RequestHost=~\"${host:text}\" error=\"\" [$__interval]))",
     "legendFormat": "{{RequestMethod}} - {{RequestPath}} - {{DownstreamStatus}}"
    }
   ]
  },
  {
   "title": "Top Redirects",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 9, "y": 20 },
   "targets": [
    {
     "expr": "topk(25, sum by (DownstreamStatus, RequestPath, downstream_Location) (count_over_time({k8s_app=\"traefik-ingress-lb\"} | json | RequestHost=~\"${host:text}\" error=\"\" DownstreamStatus=~\"3.+\" [$__interval])))",
     "legendFormat": "{{DownstreamStatus}} - {{RequestPath}} => {{downstream_Location}}"
    }
   ]
  },
  {
   "title": "Top Errors",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "topk(25, sum by (RequestMethod, DownstreamStatus, RequestPath) (count_over_time({k8s_app=\"traefik-ingress-lb\"} | json | RequestHost=~\"${host:text}\" error=\"\" DownstreamStatus=~\"[54].+\"  DownstreamStatus!=\"404\" [$__interval])))",
     "legendFormat": "{{DownstreamStatus}} - {{RequestMethod}} - {{RequestPath}}"
    }
   ]
  }
 ]
}