apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: inlets
  labels:
    app: grafana
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  tls:
  - hosts:
    - grafana.cluster.fun
    secretName: grafana-ingress
  rules:
  - host: grafana.cluster.fun
    http:
      paths:
      - path: /
        backend:
          serviceName: auth-proxy
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: inlets
  labels:
    app: prometheus
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  tls:
  - hosts:
    - prometheus.cluster.fun
    secretName: prometheus-ingress
  rules:
  - host: prometheus.cluster.fun
    http:
      paths:
      - path: /
        backend:
          serviceName: auth-proxy
          servicePort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-credentials
  namespace: monitoring
  annotations:
    kube-1password: m7c2n5gqybiyxj6ylydju2nljm
    kube-1password/vault: Kubernetes
type: Opaque
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-cloud
  namespace: monitoring
  labels:
    app: prometheus-cloud
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: prometheus-credentials
spec:
  tls:
  - hosts:
    - prometheus-cloud.cluster.fun
    secretName: prometheus-cloud-ingress
  rules:
  - host: prometheus-cloud.cluster.fun
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus-server
          servicePort: 80
