apiVersion: v1
kind: Service
metadata:
  name: base64
  namespace: base64
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: web
    name: web
  selector:
    app: base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: base64
  namespace: base64
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base64
  template:
    metadata:
      labels:
        app: base64
    spec:
      imagePullSecrets:
        - name: docker-config
      containers:
      - name: web
        image: rg.fr-par.scw.cloud/averagemarcus/base64:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
        resources:
          limits:
            memory: 5Mi
          requests:
            memory: 5Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: base64
  namespace: base64
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - base64.cluster.fun
    secretName: base64-ingress
  rules:
  - host: base64.cluster.fun
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: base64
            port:
              number: 80
