
apiVersion: v1
kind: Secret
metadata:
  name: tank
  namespace: tank
  annotations:
    kube-1password: g6xle67quzowvvekf6zukjbbm4
    kube-1password/vault: Kubernetes
    kube-1password/secret-text-parse: "true"
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: tank
  namespace: tank
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: web
  selector:
    app: tank
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tank
  namespace: tank
  labels:
    app: tank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tank
  template:
    metadata:
      labels:
        app: tank
    spec:
      containers:
      - name: web
        image: rg.fr-par.scw.cloud/averagemarcus/tank:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: tank
        ports:
        - containerPort: 3000
          name: web
        resources:
          limits:
            memory: 10Mi
          requests:
            memory: 10Mi
