apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sonarr
  namespace: inlets
  labels:
    app: sonarr
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  tls:
  - hosts:
    - sonarr.cluster.fun
    secretName: sonarr-ingress
  rules:
  - host: sonarr.cluster.fun
    http:
      paths:
      - path: /
        backend:
          serviceName: auth-proxy
          servicePort: 80
