apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: gitea-binding
  namespace: tekton-pipelines
spec:
  params:
  - name: gitrevision
    value: $(body.commit_sha)
  - name: gitref
    value: $(body.ref)
  - name: gitrepositoryurl
    value: $(body.repository.html_url)
  - name: gitbranch
    value: $(body.branch)
  - name: projectname
    value: $(body.repository.name)
  - name: isprivate
    value: $(body.repository.private)
  - name: prid
    value: $(body.number)
