
apiVersion: v1
kind: Secret
metadata:
  name: mastodon
  namespace: mastodon
  labels:
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/instance: mastodon
  annotations:
    kube-1password: wjhd3mxtyqslcu7sc4tfihm2dy
    kube-1password/vault: Kubernetes
    kube-1password/secret-text-parse: "true"
type: Opaque

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mastodon-env
  namespace: mastodon
  labels:
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/instance: mastodon
data:
  DEFAULT_LOCALE: en
  LOCAL_DOMAIN: k8s.social
  MALLOC_ARENA_MAX: "2"
  NODE_ENV: "production"
  RAILS_ENV: "production"
  STREAMING_CLUSTER_NUM: "2"
  WEB_CONCURRENCY: "2"
---