
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mastodon
  namespace: mastodon
  labels:
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/instance: "k8s.social"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 40m
spec:
  tls:
    - hosts:
        - "k8s.social"
        - "streaming.k8s.social"
      secretName: mastodon-tls
  rules:
    - host: "k8s.social"
      http:
        paths:
          - path: /
            backend:
              service:
                name: mastodon-web
                port:
                  number: 3000
            pathType: ImplementationSpecific
          - path: /api/v1/streaming
            backend:
              service:
                name: mastodon-streaming
                port:
                  number: 4000
            pathType: ImplementationSpecific
---
