apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mastodon-web
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mastodon
      app.kubernetes.io/instance: "k8s.social"
      app.kubernetes.io/component: web

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mastodon-streaming
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mastodon
      app.kubernetes.io/instance: "k8s.social"
      app.kubernetes.io/component: streaming

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mastodon-sidekiq
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mastodon
      app.kubernetes.io/instance: "k8s.social"
      app.kubernetes.io/component: sidekiq

---
