apiVersion: v1
kind: Service
metadata:
  name: cel-tester
  namespace: cel-tester
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: web
    name: web
  selector:
    app: cel-tester
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cel-tester
  namespace: cel-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cel-tester
  template:
    metadata:
      labels:
        app: cel-tester
    spec:
      containers:
      - name: web
        image: rg.fr-par.scw.cloud/averagemarcus/cel-tester:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
        resources:
          limits:
            memory: 20Mi
          requests:
            memory: 20Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cel-tester
  namespace: cel-tester
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
  - hosts:
    - cel-tester.cluster.fun
    secretName: cel-tester-ingress
  rules:
  - host: cel-tester.cluster.fun
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: cel-tester
            port:
              number: 80

