apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: csi.scaleway.com
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/csi-scaleway-com
  name: pvc-df17f08f-a966-40a0-bc72-26cf2adb89a1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  csi:
    driver: csi.scaleway.com
    fsType: ext4
    volumeAttributes:
      encrypted: "false"
      storage.kubernetes.io/csiProvisionerIdentity: 1658355449315-8081-csi.scaleway.com
    volumeHandle: fr-par-1/d823f97e-7ef0-4fb0-97ac-5a838356c355
  persistentVolumeReclaimPolicy: Retain
  storageClassName: scw-bssd
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: focalboard
  namespace: focalboard
  labels:
    app.kubernetes.io/name: focalboard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: pvc-df17f08f-a966-40a0-bc72-26cf2adb89a1

---
