apiVersion: v1
kind: Service
metadata:
  name: loki-distributed
  namespace: auth-proxy
  annotations:
    tailscale.com/tailnet-fqdn: loki-distributed-ingress.tail4dfb.ts.net
spec:
  externalName: placeholder
  type: ExternalName
