apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: csi.scaleway.com
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/csi-scaleway-com
  name: pvc-2fee8e5b-4e91-4d9a-8721-58e62c7a0a53
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: csi.scaleway.com
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1591355612436-1847-csi.scaleway.com
    volumeHandle: fr-par-1/85ad772e-b2f2-4ba5-8706-b2381223cf4d
  persistentVolumeReclaimPolicy: Retain
  storageClassName: scw-bssd
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: node-red
  namespace: node-red
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pvc-2fee8e5b-4e91-4d9a-8721-58e62c7a0a53
---
