# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pvc-2fee8e5b-4e91-4d9a-8721-58e62c7a0a53
# spec:
#   accessModes:
#   - ReadWriteOnce
#   capacity:
#     storage: 5Gi
#   csi:
#     driver: csi.scaleway.com
#     fsType: ext4
#   persistentVolumeReclaimPolicy: Retain
#   volumeMode: Filesystem
# ---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: node-red
  namespace: node-red
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
