apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: node-red
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: node-red
  updatePolicy:
    updateMode: "Auto"
