apiVersion: v1
kind: Secret
metadata:
  name: gitea-access-token
  namespace: tekton-pipelines
  annotations:
    kube-1password: u45tpgj33bnxl6iz3kwgaf44va
    kube-1password/vault: Kubernetes
    kube-1password/password-key: access-token
type: Opaque

---

apiVersion: v1
kind: Secret
metadata:
  name: gitea-creds
  annotations:
    kube-1password: 3jgo56jlsrdxilf2vdp5zsw6lq
    kube-1password/vault: Kubernetes
    tekton.dev/git-0: https://git.cluster.fun
type: Opaque
