apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-project
  namespace: tekton-pipelines
secrets:
  - name: docker-creds
  - name: gitea-creds

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pr-project
  namespace: tekton-pipelines
secrets:
  - name: docker-creds
  - name: gitea-creds
