apiVersion: v1
kind: Service
metadata:
  name: svg-to-dxf
  namespace: svg-to-dxf
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: web
    name: web
  selector:
    app: svg-to-dxf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svg-to-dxf
  namespace: svg-to-dxf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svg-to-dxf
  template:
    metadata:
      labels:
        app: svg-to-dxf
    spec:
      containers:
      - name: web
        image: rg.fr-par.scw.cloud/averagemarcus/svg-to-dxf:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: web
        resources:
          requests:
            memory: 100Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: svg-to-dxf
  namespace: svg-to-dxf
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/buffering: |
      maxrequestbodybytes: 31457280
      memrequestbodybytes: 62914560
spec:
  tls:
  - hosts:
    - svg-to-dxf.cluster.fun
    secretName: svg-to-dxf-ingress
  rules:
  - host: svg-to-dxf.cluster.fun
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: svg-to-dxf
            port:
              number: 80
