apiVersion: v1
kind: Secret
metadata:
  name: auth-proxy
  namespace: auth-proxy
  annotations:
    kube-1password: mr6spkkx7n3memkbute6ojaarm
    kube-1password/vault: Kubernetes
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: auth-proxy
  annotations:
    kube-1password: 2cqycmsgv5r7vcyvjpblcl2l4y
    kube-1password/vault: Kubernetes
type: Opaque
---
