apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-matrix-user-media
  namespace: chat
  labels:
    app.kubernetes.io/name: "matrix"
    component: synapse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
  storageClassName: sbs-default-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-matrix-signing-key
  namespace: chat
  labels:
    app.kubernetes.io/name: "matrix"
    component: synapse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sbs-default-retain
---
