apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: goplayground
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: goplayground
  updatePolicy:
    updateMode: "Auto"
