apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anniversary
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster.fun
  destination:
    namespace: anniversary
    name: cluster-fun (scaleway)
  source:
    path: manifests/11-year-anniversary
    repoURL: "https://git.cluster.fun/AverageMarcus/cluster.fun.git"
    targetRevision: HEAD
  syncPolicy:
  #   automated: {}
    syncOptions:
      - CreateNamespace=true
