apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base64
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster.fun
  destination:
    namespace: base64
    name: cluster-fun (scaleway)
  source:
    path: manifests/base64
    repoURL: "https://git.cluster.fun/AverageMarcus/cluster.fun.git"
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /data
  - group: apps
    kind: Deployment
    jqPathExpressions:
    - .spec.template.spec.containers[]?.image
