apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-civo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster.fun
  destination:
    namespace: cert-manager
    name: civo
  source:
    path: manifests/certmanager-civo
    repoURL: "https://git.cluster.fun/AverageMarcus/cluster.fun.git"
    targetRevision: HEAD
  syncPolicy:
    automated: {}
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /data
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-fun-cert-manager-issuer
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster.fun
  destination:
    namespace: cert-manager
    name: cluster-fun (v2)
  source:
    path: manifests/certmanager_chart
    repoURL: "https://git.cluster.fun/AverageMarcus/cluster.fun.git"
    targetRevision: HEAD
  syncPolicy:
    automated: {}
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /data
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-fun-cert-manager-chart
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster.fun
  destination:
    namespace: cert-manager
    name: cluster-fun (v2)
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: 1.11.0
    chart: cert-manager
    helm:
      version: v3
      values: |-
        installCRDs: "true"
        resources:
          requests:
            memory: 32Mi
          limits:
            memory: 64Mi
  syncPolicy:
    automated: {}

---
