apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grocy
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: grocy
    name: cluster-fun (scaleway)
  source:
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 6.3.1
    chart: grocy
    helm:
      values: |
        env:
          TZ: Europe/London
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            traefik.ingress.kubernetes.io/frontend-entry-points: http,https
            traefik.ingress.kubernetes.io/redirect-entry-point: https
            traefik.ingress.kubernetes.io/redirect-permanent: "true"
          hosts:
          - host: grocy.cluster.fun
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - grocy.cluster.fun
            secretName: grocy
        persistence:
          config:
            enabled: true
        probes:
          startup:
            enabled: false

  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /data
