apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: link
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster.fun
  destination:
    namespace: link
    name: cluster-fun (v2)
  source:
    path: manifests/link
    repoURL: "https://git.cluster.fun/AverageMarcus/cluster.fun.git"
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
