apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster.fun
  destination:
    namespace: chat
    name: cluster-fun (scaleway)
  source:
    path: manifests/matrix_chart
    repoURL: "https://git.cluster.fun/AverageMarcus/cluster.fun.git"
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /data

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-matrix
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster.fun
  destination:
    namespace: chat
    name: cluster-fun (scaleway)
  source:
    repoURL: 'https://dacruz21.github.io/helm-charts'
    targetRevision: 2.7.0
    chart: matrix
    helm:
      version: v3
      values: |-
        matrix:
          serverName: "matrix.cluster.fun"
          telemetry: false
          hostname: "matrix.cluster.fun"
          presence: "true"
          blockNonAdminInvites: false
          enableSearch: "true"
          adminEmail: "matrix@marcusnoble.co.uk"
          uploads:
            maxSize: 500M
            maxPixels: 64M
          federation:
            enabled: false
            allowPublicRooms: false
            blacklist:
              - '127.0.0.0/8'
              - '10.0.0.0/8'
              - '172.16.0.0/12'
              - '192.168.0.0/16'
              - '100.64.0.0/10'
              - '169.254.0.0/16'
              - '::1/128'
              - 'fe80::/64'
              - 'fc00::/7'
          registration:
            enabled: false
            allowGuests: false
          urlPreviews:
            enabled: true
            rules:
              maxSize: 10M
              ip:
                blacklist:
                  - '127.0.0.0/8'
                  - '10.0.0.0/8'
                  - '172.16.0.0/12'
                  - '192.168.0.0/16'
                  - '100.64.0.0/10'
                  - '169.254.0.0/16'
                  - '::1/128'
                  - 'fe80::/64'
                  - 'fc00::/7'

        volumes:
          media:
            capacity: 4Gi
          signingKey:
            capacity: 1Gi

        postgresql:
          enabled: true
          persistence:
            size: 4Gi

        synapse:
          image:
            repository: "matrixdotorg/synapse"
            tag: v1.43.0
            pullPolicy: IfNotPresent
          service:
            type: ClusterIP
            port: 80
          replicaCount: 1
          resources: {}
          metrics:
            enabled: true
            port: 9000
            annotations: true

        riot:
          enabled: true
          integrations:
            enabled: true
            ui: "https://scalar.vector.im/"
            api: "https://scalar.vector.im/api"
            widgets:
              - "https://scalar.vector.im/_matrix/integrations/v1"
              - "https://scalar.vector.im/api"
              - "https://scalar-staging.vector.im/_matrix/integrations/v1"
              - "https://scalar-staging.vector.im/api"
              - "https://scalar-staging.riot.im/scalar/api"
          # Experimental features in riot-web, see https://github.com/vector-im/riot-web/blob/develop/docs/labs.md
          labs:
            - feature_pinning
            - feature_custom_status
            - feature_state_counters
            - feature_many_integration_managers
            - feature_mjolnir
            - feature_dm_verification
            - feature_bridge_state
            - feature_presence_in_room_list
            - feature_custom_themes
            - feature_new_spinner
          # Servers to show in the Explore menu (the current server is always shown)
          roomDirectoryServers: []
          # Prefix before permalinks generated when users share links to rooms, users, or messages. If running an unfederated Synapse, set the below to the URL of your Riot instance.
          permalinkPrefix: "https://chat.cluster.fun"
          image:
            repository: "vectorim/element-web"
            tag: v1.9.8
            pullPolicy: IfNotPresent
          service:
            type: ClusterIP
            port: 80
          replicaCount: 2
          resources: {}

        # Settings for Coturn TURN relay, used for routing voice calls
        coturn:
          enabled: false

        mail:
          enabled: false
          relay:
            enabled: false

        bridges:
          irc:
            enabled: false
          whatsapp:
            enabled: false
          discord:
            enabled: false

        networkPolicies:
          enabled: false

        ingress:
          enabled: false
  syncPolicy:
    automated: {}
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /data
