apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-lb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster.fun
  destination:
    namespace: kube-system
    name: cluster-fun (scaleway)
  source:
    path: manifests/nginx-lb
    repoURL: "https://git.cluster.fun/AverageMarcus/cluster.fun.git"
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /data
---
