apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster.fun
  destination:
    namespace: kube-system
    name: cluster-fun (scaleway)
  source:
    repoURL: 'https://stakater.github.io/stakater-charts'
    targetRevision: v0.0.89
    chart: reloader
  syncPolicy:
    automated: {}
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /data
