apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster.fun
  destination:
    namespace: tailscale
    name: scaleway
  sources:
  - path: manifests/tailscale-operator
    repoURL: "https://git.cluster.fun/AverageMarcus/cluster.fun.git"
    targetRevision: HEAD
  - repoURL: 'https://github.com/tailscale/tailscale.git'
    path: "main/cmd/k8s-operator/deploy/chart"
    targetRevision: HEAD
    chart: tailscale-operator
    helm:
      version: v3
      values: |-
        operatorConfig:
          hostname: "scaleway"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

---
