apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-proxy-services
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster.fun
  destination:
    namespace: auth-proxy
    name: scaleway
  source:
    path: manifests/tailscale-proxy-services
    repoURL: "https://git.cluster.fun/AverageMarcus/cluster.fun.git"
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /data
---
