apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twitter-to-airtable
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster.fun
  destination:
    namespace: twitter-to-airtable
    name: civo
  source:
    path: manifests/twitter-to-airtable
    repoURL: "https://git.cluster.fun/AverageMarcus/cluster.fun.git"
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /data
  - group: apps
    kind: Deployment
    jqPathExpressions:
    - .spec.template.spec.containers[]?.image
