apiVersion: v1
kind: Service
metadata:
  name: talks
  namespace: talks
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: web
    name: web
  selector:
    app: talks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: talks
  namespace: talks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: talks
  template:
    metadata:
      labels:
        app: talks
    spec:
      containers:
      - name: web
        image: harbor.cluster.fun/averagemarcus/talks:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
        resources:
          limits:
            memory: 50Mi
          requests:
            memory: 50Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: talks
  namespace: talks
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - talks.marcusnoble.co.uk
    secretName: talks-ingress
  rules:
  - host: talks.marcusnoble.co.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: talks
            port:
              number: 80

