apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: talks
  namespace: talks
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/permanent-redirect: https://speaking.marcusnoble.co.uk
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - talks.marcusnoble.co.uk
    secretName: talks-ingress
  rules:
  - host: talks.marcusnoble.co.uk
