apiVersion: v1
kind: Secret
metadata:
  name: docker-config
  namespace: calendso
  annotations:
    kube-1password: i6ngbk5zf4k52xgwdwnfup5bby
    kube-1password/vault: Kubernetes
    kube-1password/secret-text-key: .dockerconfigjson
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30=
---
apiVersion: v1
kind: Secret
metadata:
  name: calendso
  namespace: calendso
  annotations:
    kube-1password: shgjmetsq7fcizmzzdn5ishzxu
    kube-1password/vault: Kubernetes
    kube-1password/secret-text-parse: "true"
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: calendso
  namespace: calendso
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: web
    name: web
  selector:
    app.kubernetes.io/name: calendso
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendso
  namespace: calendso
  labels:
    app.kubernetes.io/name: calendso
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: calendso
  template:
    metadata:
      labels:
        app.kubernetes.io/name: calendso
    spec:
      imagePullSecrets:
        - name: docker-config
      containers:
      - name: web
        image: docker.cluster.fun/private/calendso:latest
        imagePullPolicy: Always
        env:
        - name: BASE_URL
          value: "https://meet.marcusnoble.co.uk"
        - name: NEXT_PUBLIC_APP_URL
          value: "https://meet.marcusnoble.co.uk"
        - name: SINGLE_USER
          value: "AverageMarcus"
        - name: NODE_ENV
          value: production
        - name: POSTGRES_DB
          value: calendso
        envFrom:
        - secretRef:
            name: calendso
        ports:
        - containerPort: 3000
          name: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calendso
  namespace: calendso
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - meet.marcusnoble.co.uk
    secretName: calendso-ingress
  rules:
  - host: meet.marcusnoble.co.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: calendso
            port:
              number: 80
