apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: radarr
  namespace: inlets
  labels:
    app: radarr
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  tls:
  - hosts:
    - radarr.cluster.fun
    secretName: radarr-ingress
  rules:
  - host: radarr.cluster.fun
    http:
      paths:
      - path: /
        backend:
          serviceName: auth-proxy
          servicePort: 80
