apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  namespace: inlets
  labels:
    app: radarr
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - radarr.cluster.fun
    secretName: radarr-ingress
  rules:
  - host: radarr.cluster.fun
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: auth-proxy
            port:
              number: 80
