apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-credentials
  labels:
    app: vaultwarden
    app.kubernetes.io/name: vaultwarden
  annotations:
    kube-1password: e75k7oktk43v4mmvbs24vyelwy
    kube-1password/vault: Kubernetes
    kube-1password/secret-text-parse: "true"
type: Opaque

---

apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-smtp
  labels:
    app: vaultwarden
    app.kubernetes.io/name: vaultwarden
  annotations:
    kube-1password: 3kiighdh7la4wdfiv5fzgm34yu
    kube-1password/vault: Kubernetes
    kube-1password/secret-text-parse: "true"
type: Opaque

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-config
  labels:
    app: vaultwarden
    app.kubernetes.io/name: vaultwarden
data:
  DOMAIN: "https://vault.cluster.fun"

  # Signup Controls
  SIGNUPS_ALLOWED: "false"
  INVITATIONS_ALLOWED: "true"
  INVITATION_ORG_NAME: "Noble"

  # Security
  SHOW_PASSWORD_HINT: "false"
  EXTENDED_LOGGING: "true"
  LOG_LEVEL: "info"
  REQUIRE_DEVICE_EMAIL: "true"

