apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
  labels:
    app: vaultwarden
    app.kubernetes.io/name: vaultwarden
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: sfs-standard-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-attachments
  labels:
    app: vaultwarden
    app.kubernetes.io/name: vaultwarden
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: sfs-standard-retain
